name: 'AutoFormat'
on:
  issue_comment:
    types: ['created', 'edited']

jobs:
  format:
    runs-on: 'ubuntu-latest'
    if: "github.event.issue.pull_request && contains(github.event.comment.body, '/pr-command:autoformat')"
    container:
      image: 'docker.io/ubuntu:latest'
    steps:
      - name: "Dependencies"
        run: 'apt update && apt install -y git clang-format'
      - uses: 'actions/checkout@v3'
        with:
          submodules: 'recursive'
      - name: 'clang-format'
        shell: 'bash'
        run: 'find include src -iname "*.h" -or -iname "*.cc" | xargs clang-format -i --style=file --Werror'
      - name: 'Workaround file ownership errors'
        shell: 'bash'
        run: 'git config --global --add safe.directory $GITHUB_WORKSPACE'
      - uses: 'EndBug/add-and-commit@v9'
        with:
          add: "['src', 'include']"
          message: 'lint(*): fix formatting'
          default_author: 'github_actor'
          push: true

